In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso, LassoCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [3]:
df = pd.read_csv("clean_algebrian_forest_fires_dataset.csv")
df.head()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes_not fire
0,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,1.0
1,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,1.0
2,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,1.0
3,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,1.0
4,27.0,77.0,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,1.0

## Lasso Model

In [4]:
print("="*65)
print("Model after droping FFMC with Lasso")
print("="*65)


X=df.drop(columns=["FWI","FFMC"])
y=df["FWI"]


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["variable"] = X.columns

vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lasso = Lasso()
lasso.fit(X_train_scaled, y_train)

y_pred = lasso.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
adj_r2 = 1 - ((1-r2)*(len(y_test)-1)/(len(y_test) - X_train.shape[1] - 1))

print("mse", mse)
print("mae", mae)
print("rmse", rmse)
print("r2", r2)
print("adj_r2", adj_r2)

=================================================================
Model after droping FFMC with Lasso
=================================================================
           variable         VIF
0       Temperature   34.929630
1                RH   30.564180
2                Ws   36.309623
3              Rain    1.449702
4               DMC  186.137390
5                DC   50.762872
6               ISI   10.793800
7               BUI  379.555807
8  Classes_not fire    4.227526
mse 4.353213399155511
mae 1.2710039205488506
rmse 2.0864355727305623
r2 0.9050106533232942
adj_r2 0.883090034859439

In [5]:
print("="*65)
print("Model after droping FFMC with Lasso")
print("="*65)


X=df.drop(columns=["FWI","DMC"])
y=df["FWI"]


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["variable"] = X.columns

vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lasso = Lasso()
lasso.fit(X_train_scaled, y_train)

y_pred = lasso.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
adj_r2 = 1 - ((1-r2)*(len(y_test)-1)/(len(y_test) - X_train.shape[1] - 1))

print("mse", mse)
print("mae", mae)
print("rmse", rmse)
print("r2", r2)
print("adj_r2", adj_r2)

=================================================================
Model after droping FFMC with Lasso
=================================================================
           variable         VIF
0       Temperature  116.560008
1                RH   30.398773
2                Ws   37.976649
3              Rain    1.651086
4              FFMC  106.809187
5                DC   23.000002
6               ISI   10.813291
7               BUI   32.567491
8  Classes_not fire    4.668952
mse 4.040627795832559
mae 1.1882375882193064
rmse 2.0101312882079516
r2 0.9118314313366007
adj_r2 0.891484838568124

In [6]:
print("="*65)
print("Model after droping BUI with Lasso")
print("="*65)


X=df.drop(columns=["FWI","BUI"])
y=df["FWI"]


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["variable"] = X.columns

vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lasso = Lasso()
lasso.fit(X_train_scaled, y_train)

y_pred = lasso.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
adj_r2 = 1 - ((1-r2)*(len(y_test)-1)/(len(y_test) - X_train.shape[1] - 1))

print("mse", mse)
print("mae", mae)
print("rmse", rmse)
print("r2", r2)
print("adj_r2", adj_r2)

=================================================================
Model after droping BUI with Lasso
=================================================================
           variable         VIF
0       Temperature  116.619407
1                RH   30.385921
2                Ws   38.109064
3              Rain    1.647180
4              FFMC  106.664536
5               DMC   15.949744
6                DC   10.508974
7               ISI   10.851441
8  Classes_not fire    4.692042
mse 4.793205892307253
mae 1.354296547859683
rmse 2.1893391451091477
r2 0.8954097916988109
adj_r2 0.8712735897831518

## LassoCV

In [7]:
print("="*65)
print("Model after droping FFMC with LassoCV")
print("="*65)


X=df.drop(columns=["FWI","FFMC"])
y=df["FWI"]


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["variable"] = X.columns

vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lasso = LassoCV()
lasso.fit(X_train_scaled, y_train)

y_pred = lasso.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
adj_r2 = 1 - ((1-r2)*(len(y_test)-1)/(len(y_test) - X_train.shape[1] - 1))

print("mse", mse)
print("mae", mae)
print("rmse", rmse)
print("r2", r2)
print("adj_r2", adj_r2)

=================================================================
Model after droping FFMC with LassoCV
=================================================================
           variable         VIF
0       Temperature   34.929630
1                RH   30.564180
2                Ws   36.309623
3              Rain    1.449702
4               DMC  186.137390
5                DC   50.762872
6               ISI   10.793800
7               BUI  379.555807
8  Classes_not fire    4.227526
mse 0.7040010044282786
mae 0.6433496336096839
rmse 0.8390476770888998
r2 0.9767720993112005
adj_r2 0.9714118145368621

In [8]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LassoCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor

print("=" * 65)
print("Model after dropping DMC with LassoCV")
print("=" * 65)

# 1. Define Features and Target
X = df.drop(columns=["FWI", "DMC"])
y = df["FWI"]

# 2. Check Multicollinearity (VIF)
vif_data = pd.DataFrame()
vif_data["variable"] = X.columns
vif_data["VIF"] = [
    variance_inflation_factor(X.values, i) for i in range(X.shape[1])
]
print("Variance Inflation Factor (VIF):")
print(vif_data)
print("-" * 65)

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Fit LassoCV Model
lassoCV = LassoCV(cv=5)  # cv=5 ensures robust cross-validation
lassoCV.fit(X_train_scaled, y_train)

# 6. Generate Predictions
y_pred_train = lassoCV.predict(X_train_scaled)
y_pred_test = lassoCV.predict(X_test_scaled)

# 7. Evaluate Performance (Train vs Test)
r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

# Adjusted R2 Calculation Formula
n_train, p = X_train.shape
n_test = len(y_test)

adj_r2_train = 1 - ((1 - r2_train) * (n_train - 1) / (n_train - p - 1))
adj_r2_test = 1 - ((1 - r2_test) * (n_test - 1) / (n_test - p - 1))

# Error Metrics on Test Set
mse = mean_squared_error(y_test, y_pred_test)
mae = mean_absolute_error(y_test, y_pred_test)
rmse = np.sqrt(mse)

# 8. Print Diagnostic Metrics
print(f"Train R2 Score: {r2_train:.4f}")
print(f"Train Adjusted R2: {adj_r2_train:.4f}")
print(f"Test R2 Score: {r2_test:.4f}")
print(f"Test Adjusted R2: {adj_r2_test:.4f}\n")

print("--- Overfitting vs Underfitting Analysis ---")
if r2_train > 0.85 and (r2_train - r2_test) > 0.10:
    print("Diagnosis: Potential OVERFITTING. High train score, but test score drops significantly.")
elif r2_train < 0.60 and r2_test < 0.60:
    print("Diagnosis: Potential UNDERFITTING. Both train and test scores are low.")
else:
    print("Diagnosis: GOOD FIT. The model generalizes well to unseen data.")
print("-" * 65)

print("Test Set Error Metrics:")
print(f"MSE:  {mse:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"RMSE: {rmse:.4f}")


import joblib

joblib.dump(scaler, "StandardLassoCV.joblib")
joblib.dump(lassoCV, "LassoCVlinearRegression.joblib")
print('files saved successfully')

=================================================================
Model after dropping DMC with LassoCV
=================================================================
Variance Inflation Factor (VIF):
           variable         VIF
0       Temperature  116.560008
1                RH   30.398773
2                Ws   37.976649
3              Rain    1.651086
4              FFMC  106.809187
5                DC   23.000002
6               ISI   10.813291
7               BUI   32.567491
8  Classes_not fire    4.668952
-----------------------------------------------------------------

Train R2 Score: 0.9727
Train Adjusted R2: 0.9713
Test R2 Score: 0.9892
Test Adjusted R2: 0.9867

--- Overfitting vs Underfitting Analysis ---
Diagnosis: GOOD FIT. The model generalizes well to unseen data.
-----------------------------------------------------------------
Test Set Error Metrics:
MSE:  0.3269
MAE:  0.4056
RMSE: 0.5717
files saved successfully

In [9]:
print("="*65)
print("Model after droping BUI with LassoCV")
print("="*65)


X=df.drop(columns=["FWI","BUI"])
y=df["FWI"]


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["variable"] = X.columns

vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lasso = LassoCV()
lasso.fit(X_train_scaled, y_train)

y_pred = lasso.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
adj_r2 = 1 - ((1-r2)*(len(y_test)-1)/(len(y_test) - X_train.shape[1] - 1))

print("mse", mse)
print("mae", mae)
print("rmse", rmse)
print("r2", r2)
print("adj_r2", adj_r2)

=================================================================
Model after droping BUI with LassoCV
=================================================================

           variable         VIF
0       Temperature  116.619407
1                RH   30.385921
2                Ws   38.109064
3              Rain    1.647180
4              FFMC  106.664536
5               DMC   15.949744
6                DC   10.508974
7               ISI   10.851441
8  Classes_not fire    4.692042
mse 0.7578236618226347
mae 0.48005952499171617
rmse 0.8705306782777014
r2 0.974996267554002
adj_r2 0.9692261754510795

In [10]:
seeds = [7, 42, 100, 123, 2024]

feature_sets = {
    "drop_FFMC": ["FWI", "FFMC"],
    "drop_DMC": ["FWI", "DMC"],
    "drop_BUI": ["FWI", "BUI"],
}

model_factories = {
    "Lasso": Lasso,
    "LassoCV": LassoCV,
}

def get_alpha_value(model):
    if hasattr(model, "alpha_"):
        return model.alpha_
    if hasattr(model, "alpha"):
        return model.alpha
    return None

def run_model_sweep(model_name, model_factory):
    results = []

    for seed in seeds:
        for feature_name, drop_cols in feature_sets.items():
            X = df.drop(columns=drop_cols)
            y = df["FWI"]

            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=seed
            )

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled = scaler.transform(X_test)

            model = model_factory()
            model.fit(X_train_scaled, y_train)
            y_pred = model.predict(X_test_scaled)

            mse = mean_squared_error(y_test, y_pred)
            mae = mean_absolute_error(y_test, y_pred)
            rmse = np.sqrt(mse)
            r2 = r2_score(y_test, y_pred)
            adj_r2 = 1 - ((1 - r2) * (len(y_test) - 1) / (len(y_test) - X_train.shape[1] - 1))

            results.append({
                "seed": seed,
                "feature_set": feature_name,
                "mse": mse,
                "mae": mae,
                "rmse": rmse,
                "r2": r2,
                "adj_r2": adj_r2,
                "alpha": get_alpha_value(model),
            })

    results_df = pd.DataFrame(results)

    print("=" * 65)
    print(f"The result for the model {model_name}")
    print("=" * 65)

    print("Results for seed 100:")
    display(results_df[results_df["seed"] == 100].sort_values("r2", ascending=False))

    print("Best feature set for each seed:")
    best_per_seed = results_df.loc[results_df.groupby("seed")["r2"].idxmax()]
    display(best_per_seed[["seed", "feature_set", "r2", "rmse", "mse", "mae", "alpha"]].sort_values("seed"))

    print("How often each feature set won:")
    display(best_per_seed["feature_set"].value_counts().rename_axis("feature_set").reset_index(name="wins"))

    print("Full comparison table:")
    display(results_df.sort_values(["seed", "r2"], ascending=[True, False]))

    return results_df

all_results = {}
for model_name, model_factory in model_factories.items():
    all_results[model_name] = run_model_sweep(model_name, model_factory)

=================================================================
The result for the model Lasso
=================================================================
Results for seed 100:

   seed feature_set       mse       mae      rmse        r2    adj_r2  alpha
7   100    drop_DMC  4.040628  1.188238  2.010131  0.911831  0.891485    1.0
6   100   drop_FFMC  4.353213  1.271004  2.086436  0.905011  0.883090    1.0
8   100    drop_BUI  4.793206  1.354297  2.189339  0.895410  0.871274    1.0

Best feature set for each seed:

    seed feature_set        r2      rmse       mse       mae  alpha
1      7    drop_DMC  0.948109  1.789690  3.202992  1.185144    1.0
4     42    drop_DMC  0.958468  1.121949  1.258770  0.898546    1.0
7    100    drop_DMC  0.911831  2.010131  4.040628  1.188238    1.0
10   123    drop_DMC  0.913603  2.252903  5.075570  1.462729    1.0
14  2024    drop_BUI  0.944275  2.047611  4.192711  1.561570    1.0

How often each feature set won:

  feature_set  wins
0    drop_DMC     4
1    drop_BUI     1

Full comparison table:

    seed feature_set       mse       mae      rmse        r2    adj_r2  alpha
1      7    drop_DMC  3.202992  1.185144  1.789690  0.948109  0.936134    1.0
0      7   drop_FFMC  3.423515  1.249103  1.850274  0.944536  0.931737    1.0
2      7    drop_BUI  3.917746  1.339136  1.979330  0.936529  0.921882    1.0
4     42    drop_DMC  1.258770  0.898546  1.121949  0.958468  0.948884    1.0
3     42   drop_FFMC  1.430788  0.955270  1.196156  0.952792  0.941898    1.0
5     42    drop_BUI  1.697137  1.002543  1.302742  0.944004  0.931082    1.0
7    100    drop_DMC  4.040628  1.188238  2.010131  0.911831  0.891485    1.0
6    100   drop_FFMC  4.353213  1.271004  2.086436  0.905011  0.883090    1.0
8    100    drop_BUI  4.793206  1.354297  2.189339  0.895410  0.871274    1.0
10   123    drop_DMC  5.075570  1.462729  2.252903  0.913603  0.893665    1.0
9    123   drop_FFMC  5.375048  1.514347  2.318415  0.908505  0.887391    1.0
11   123    drop_BUI  5.766691  1.567136  2.401394  0.901839  0.879186    1.0
14  2024    drop_BUI  4.192711  1.561570  2.047611  0.944275  0.931415    1.0
12  2024   drop_FFMC  4.222558  1.551265  2.054886  0.943878  0.930927    1.0
13  2024    drop_DMC  4.408174  1.557986  2.099565  0.941411  0.927890    1.0

=================================================================
The result for the model LassoCV
=================================================================
Results for seed 100:

,seed,feature_set,mse,mae,rmse,r2,adj_r2,alpha
7,100,drop_DMC,4.606496,0.717930,2.146275,0.899484,0.876288,0.023373
8,100,drop_BUI,4.955530,0.804060,2.226102,0.891868,0.866914,0.026874
6,100,drop_FFMC,5.087259,1.012862,2.255495,0.888993,0.863377,0.007138

Best feature set for each seed:

    seed feature_set        r2      rmse       mse       mae     alpha
1      7    drop_DMC  0.989015  0.823433  0.678042  0.600397  0.011022
4     42    drop_DMC  0.989215  0.571741  0.326888  0.405559  0.038191
7    100    drop_DMC  0.899484  2.146275  4.606496  0.717930  0.023373
10   123    drop_DMC  0.914906  2.235849  4.999021  0.811911  0.024139
14  2024    drop_BUI  0.990346  0.852283  0.726387  0.625882  0.027787

How often each feature set won:

  feature_set  wins
0    drop_DMC     4
1    drop_BUI     1

Full comparison table:

,seed,feature_set,mse,mae,rmse,r2,adj_r2,alpha
1,7,drop_DMC,0.678042,0.600397,0.823433,0.989015,0.986480,0.011022
2,7,drop_BUI,0.861136,0.656104,0.927974,0.986049,0.982829,0.031392
0,7,drop_FFMC,1.100604,0.797754,1.049097,0.982169,0.978055,0.077760
4,42,drop_DMC,0.326888,0.405559,0.571741,0.989215,0.986726,0.038191
3,42,drop_FFMC,0.704001,0.643350,0.839048,0.976772,0.971412,0.094603
5,42,drop_BUI,0.757824,0.480060,0.870531,0.974996,0.969226,0.040951
7,100,drop_DMC,4.606496,0.717930,2.146275,0.899484,0.876288,0.023373
8,100,drop_BUI,4.955530,0.804060,2.226102,0.891868,0.866914,0.026874
6,100,drop_FFMC,5.087259,1.012862,2.255495,0.888993,0.863377,0.007138
10,123,drop_DMC,4.999021,0.811911,2.235849,0.914906,0.895269,0.024139
11,123,drop_BUI,5.481000,0.919033,2.341154,0.906702,0.885171,0.020995
9,123,drop_FFMC,5.711637,1.066186,2.389903,0.902776,0.880339,0.008476
14,2024,drop_BUI,0.726387,0.625882,0.852283,0.990346,0.988118,0.027787
13,2024,drop_DMC,0.839207,0.678873,0.916082,0.988846,0.986272,0.052067
12,2024,drop_FFMC,1.088077,0.809320,1.043109,0.985538,0.982201,0.045285

In [11]:
best_seed = 42
X = df.drop(columns=["FWI", "DMC"] )
y = df["FWI"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=best_seed
 )

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

best_lasso = LassoCV()
best_lasso.fit(X_train_scaled, y_train)

coef_df = pd.DataFrame({
    "feature": X.columns,
    "coefficient": best_lasso.coef_,
})
coef_df["abs_coefficient"] = coef_df["coefficient"].abs()
coef_df = coef_df.sort_values("abs_coefficient", ascending=False)

print("Selected alpha:", best_lasso.alpha_)
print("Intercept:", best_lasso.intercept_)
display(coef_df)

Selected alpha: 0.03819137664883921
Intercept: 7.420103092783506

            feature  coefficient  abs_coefficient
6               ISI     5.146213         5.146213
7               BUI     3.667458         3.667458
4              FFMC    -0.602967         0.602967
8  Classes_not fire    -0.081751         0.081751
1                RH    -0.047372         0.047372
2                Ws    -0.031257         0.031257
3              Rain     0.023107         0.023107
0       Temperature    -0.000000         0.000000
5                DC    -0.000000         0.000000